/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zmz_fmodex_VoliUtil */

#ifndef _Included_com_zmz_fmodex_VoliUtil
#define _Included_com_zmz_fmodex_VoliUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zmz_fmodex_VoliUtil
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_zmz_fmodex_VoliUtil_fix
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_zmz_fmodex_VoliUtil
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zmz_fmodex_VoliUtil_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
